project_id = "dvkpanntfxehgasngylg"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public", "auth"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[api.tls]
enabled = false

[db]
port = 54325
shadow_port = 54323
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[db.seed]
enabled = true
sql_paths = ['./seed.sql']

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "https://dvkpanntfxehgasngylg.supabase.co"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "https://tryself.ai"
additional_redirect_urls = ["https://tryself.ai"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false
enable_manual_linking = false
minimum_password_length = 6
password_requirements = ""

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
secure_password_change = false
max_frequency = "1s"
otp_length = 6
otp_expiry = 3600

[auth.external.coinbase]
enabled = true
client_id = "f9ea95af-876c-4a33-9230-bed617584e83"
secret = "jzp53bfr7CPERb.SZw_TGfW1Qz"
redirect_uri = "https://tryself.ai/auth/callback"

[edge_runtime]
enabled = true
policy = "oneshot"
inspector_port = 8083

[functions.exchange-token]
enabled = true
verify_jwt = false

[functions.send-confirmation-email]
enabled = true
verify_jwt = false

[analytics]
enabled = true
port = 54327
backend = "postgres"

[experimental]
orioledb_version = ""
s3_host = "env(S3_HOST)"
s3_region = "env(S3_REGION)"
s3_access_key = "env(S3_ACCESS_KEY)"
s3_secret_key = "env(S3_SECRET_KEY)"